CREATE TABLE IF NOT EXISTS users (
    user_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      CHARACTER VARYING(255) NOT NULL UNIQUE,
    login      CHARACTER VARYING(255) NOT NULL UNIQUE,
    user_name  CHARACTER VARYING(255),
    birthdate  DATE

    check birthdate < NOW()
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users (user_id),
    friend_id INTEGER REFERENCES users (user_id),
    is_friends BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
mpa_id   INTEGER PRIMARY KEY,
mpa_name CHARACTER VARYING(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    CHARACTER VARYING(100) NOT NULL UNIQUE,
    film_description  CHARACTER VARYING(200) NOT NULL UNIQUE,
    release_date DATE NOT NULL,
    duration     INTEGER NOT NULL,
    rate INTEGER,
    mpa_id INTEGER REFERENCES mpa (mpa_id),

    check (length(film_description)<= 200),
    check (duration > 0),
    check (release_date > DATE '1895-12-28')
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name CHARACTER VARYING(100)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id  INTEGER REFERENCES films (film_id),
    genre_id INTEGER REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER REFERENCES films (film_id),
    user_id INTEGER REFERENCES users (user_id)
);